// src/components/Landing.svelte
<section class="Landing">
	<img src="./Rodrigo_Landing.png" alt="Rodrigo holding a happy Cocker Spaniel" srcset="" />
	<div class="container">
		<h1>Rodrigo De Lemos</h1>
		<p>Dog Grooming Services</p>
		<button>Book an Appointment</button>
	</div>
</section>

<style>
	.Landing {
		min-height: 95vh;
		background: var(--color-theme-1);
		background: linear-gradient(45deg, var(--color-theme-2) 0%, var(--color-theme-1) 100%);
		color: var(--color-text-dark);
		position: relative;
		display: flex;
		align-items: flex-start;
	}

	@media (min-width: 720px) {
		.Landing {
			align-items: flex-end;
		}
	}

	.Landing .container {
		position: relative;
	}

	.Landing img {
		position: absolute;
		max-width: 80%;
		max-height: 80%;
		right: 0;
		bottom: 0;
	}

	h1 {
		font-weight: bold;
		font-size: 5rem;
		margin: 0;
		line-height: 1.1em;
	}

	p {
		font-weight: lighter;
		font-size: 2rem;
		line-height: 1em;
		margin: 0.5em 0 1em;
	}
</style>

// src/components/Landing.jsx
import LandingImage from '../assets/Rodrigo_Landing.png';

export function Landing() {
  return (
    <section className='Landing h-[95vh] relative flex md:items-end items-start text-(--color-text-dark)'>
      <img
        src={LandingImage}
        alt='Rodrigo holding a happy Cocker Spaniel'
        className='absolute max-h-[80%] max-w-[80%] right-0 bottom-0'
      />
      <div className='container absolute mx-auto max-w-[1080px] inset-0'>
        <h1 className='font-bold text-6xl md:text-8xl my-4'>Rodrigo De Lemos</h1>
        <p className='font-thin text-3xl md:text-5xl mb-16'>Dog Grooming Services</p>
      </div>
      <div className='container absolute mx-auto max-w-[1080px] inset-0'>
        <a className='button absolute bottom-8' href='tel:+351935871091'>
          Book an Appointment
        </a>
      </div>
    </section>
  );
}
