// src/components/Testimonials.jsx
import testimonialImage from "../assets/Testimonial.png";

function Item(props) {
  const { align, src, headline, signature } = props;
  return (
    <article className={`TestimonialItem ${align}`}>
      <img src={src} alt="" />
      <div>
        <h2>{headline}</h2>
        <p>{signature}</p>
      </div>
    </article>
  );
}

export function Testimonials() {
  return (
    <section className="Testimonials">
      <div className="container">
        <Item
          align="left"
          src={testimonialImage}
          headline={`“My poodle loves to play in the mud, but Rodrigo can always clean and
          care for his coat”`}
          signature={`Gabriela, and her toy Poodle, Jorge`}
        />
        <Item
          align="right"
          src={testimonialImage}
          headline={`“My poodle loves to play in the mud, but Rodrigo can always clean and
          care for his coat”`}
          signature={`Gabriela, and her toy Poodle, Jorge`}
        />
      </div>
    </section>
  );
}

// src/components/Testimonials/index.svelte
<script>
	import Item from './item.svelte';
</script>

<section class="Testimonials">
	<div class="container">
		<Item
      layout={'left'}
			author={'Gabriela, and her toy Poodle, Jorge'}
			image={'/Testimonial.png'}
			quote={'My poodle loves to play in the mud, but Rodrigo can always clean and care for his coat'}
		/>
    <Item
      layout={'right'}
			author={'Gabriela, and her toy Poodle, Jorge'}
			image={'/Testimonial.png'}
			quote={'My poodle loves to play in the mud, but Rodrigo can always clean and care for his coat'}
		/>
	</div>
</section>

<style>
	.Testimonials .container {
		padding: 0;
	}
</style>
